---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: ">_ Terminal"
    port: 443
    path: /showroom
    user: root
  - name: Placeholder
    url: /placeholder
