---
# Cluster identifier derived from GUID
ocp4_workload_konflux_tssc_cluster_name: "cluster-{{ guid }}"

# Workload control
ocp4_workload_konflux_tssc_cluster_become_override: false
ocp4_workload_konflux_tssc_cluster_silent: false
