apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: lab-policy
  namespace: enterprise-contract-service
spec:
  description: Lab policy with custom trusted tasks from quay.io/rhpds/pipeline-docker-build-lab
  name: Lab
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - name: Lab
    policy:
    - oci::quay.io/conforma/release-policy:latest@sha256:10de4ff888f9d054baeaa15c528ff74118bfd3c99ed0e5fc0ac24e72e83e01dc
    data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/konflux-ci/tekton-catalog/data-acceptable-bundles:latest
    - github.com/rhpds/konflux-tssc-lab.git//tekton/data
    config:
      exclude:
      - hermetic_task
      - source_image
      - rpm_repos
      - labels.required  # Exclude CPE label requirement for lab
      include:
      - '@redhat'
