---
- name: Get Quay API token
  kubernetes.core.k8s_info:
    kind: Secret
    name: quaytoken
    namespace: image-controller
  register: r_quay_token_secret

- name: Set Quay facts
  ansible.builtin.set_fact:
    quay_token: "{{ r_quay_token_secret.resources[0].data.quaytoken | b64decode }}"
    quay_api_url: "{{ r_quay_token_secret.resources[0].data.quayapiurl | b64decode }}"
    quay_org: "{{ r_quay_token_secret.resources[0].data.organization | b64decode }}"

- name: Add user to Quay organization members team
  ansible.builtin.uri:
    url: "{{ quay_api_url }}/organization/{{ quay_org }}/team/members/members/{{ ocp4_workload_konflux_tssc_tenant_user }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ quay_token }}"
      Content-Type: "application/json"
    status_code: [200, 201]
  register: r_quay_member

- name: Show Quay membership result
  ansible.builtin.debug:
    msg: "User {{ ocp4_workload_konflux_tssc_tenant_user }} added to Quay org {{ quay_org }} members team"
