---
# Post-workload tasks — verify the Role and RoleBinding were created

- name: Verify Konflux tenant reader Role exists
  kubernetes.core.k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: Role
    name: "{{ ocp4_workload_konflux_tssc_tenant_role_name }}"
    namespace: "{{ ocp4_workload_konflux_tssc_tenant_namespace }}"
  register: r_role
  failed_when: r_role.resources | length == 0

- name: Verify Konflux tenant reader RoleBinding exists
  kubernetes.core.k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: "{{ ocp4_workload_konflux_tssc_tenant_rolebinding_name }}"
    namespace: "{{ ocp4_workload_konflux_tssc_tenant_namespace }}"
  register: r_rolebinding
  failed_when: r_rolebinding.resources | length == 0
